services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5001
    ports:
      - "5000:80"
    networks:
      - shared-network   

networks:
  shared-network:
    driver: bridge
